# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
# cache: cocoapods
script:
 - set -o pipefail && xcodebuild -list
 - echo "==========Now Building for Tests==================="
 - set -o pipefail &&  xcodebuild -workspace SierraXCFit.xcworkspace -scheme SierraXCFit -sdk iphonesimulator -destination 'platform=iOS Simulator,id=54C3AC56-821B-405A-B4C7-B2BC2EC60650,OS=10.0' build-for-testing
 - echo "==========Now Running Only Cucumberish Tests==================="
 - set -o pipefail &&  xcodebuild -workspace SierraXCFit.xcworkspace -scheme SierraXCFit -sdk iphonesimulator -destination 'platform=iOS Simulator,id=54C3AC56-821B-405A-B4C7-B2BC2EC60650,OS=10.0' -only-testing:SierraXCFitCucumberish test-without-building