# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
before_install:
 - gem install xcpretty
 - gem install xcpretty-travis-formatter
# cache: cocoapods
script:
 # - set -o pipefail && xcodebuild -list
 # - echo "==========Now Building for Tests==================="
 # - set -o pipefail &&  xcodebuild -workspace SierraXCFit.xcworkspace -scheme SierraXCFit -sdk iphonesimulator -destination 'platform=iOS Simulator,id=7453E43C-6352-44AA-8BE0-2E09643F5F88,OS=10.0' build-for-testing | xcpretty -f `xcpretty-travis-formatter`
 # - echo "==========Now Running Only Cucumberish Tests==================="
 # - set -o pipefail &&  xcodebuild -workspace SierraXCFit.xcworkspace -scheme SierraXCFit -sdk iphonesimulator -destination 'platform=iOS Simulator,id=7453E43C-6352-44AA-8BE0-2E09643F5F88,OS=10.0' -only-testing:SierraXCFitCucumberish test-without-building
 - echo "==========Now Building target for Fitnesse ==================="
 - set -o pipefail && xcodebuild -workspace SierraXCFit.xcworkspace -scheme AcceptanceTests -sdk iphonesimulator -destination 'platform=iOS Simulator,id=7453E43C-6352-44AA-8BE0-2E09643F5F88,OS=10.0' clean build | xcpretty
 - echo "==========Now Running Fitnesse Tests ==================="
 - set -o pipefail && java -jar fitnesse-standalone.jar -v -o -c "FrontPage?suite&format=text"
